
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE0_CV(
	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	inout 		          		CLOCK4_50,


	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,
	input 		          		RESET_N,

	//////////// LED //////////
	output		     [9:0]		LEDR,


	//////////// microSD Card //////////
	output		          		SD_CLK,
	inout 		          		SD_CMD,
	inout 		     [3:0]		SD_DATA,

	//////////// SW //////////
	input 		     [9:0]		SW,


	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO_0,

	//////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO_1
	);


	
	//=======================================================
	//  REG/WIRE declarations
	//=======================================================


	logic 						CLK_100MHz;
	logic 						mosi;	
	logic 						miso;
	logic 						sclk;	
	logic 						ssn;
	logic 						clk;
	logic [15:0]				data_debug;
	

	//=======================================================
	//  Structural coding
	//=======================================================


	assign mosi				=	GPIO_0[0];
	assign sclk				=	GPIO_0[1];
	assign ssn				=	GPIO_0[2];
	assign GPIO_0[3]		=	miso;
	assign LEDR				=	data_debug;

	/*請使用PLL IP
		輸入：CLOCK_50
		輸出：CLK_100MHz
	*/
	
	SPI SPI(
		//------output--------------------------------
		.miso				(miso),
		.data_debug			(data_debug),

		//------input---------------------------------
		.mosi				(mosi),
		.sclk				(sclk),
		.ssn				(ssn),
		// .clk				(CLK_100MHz),
		.clk				(CLOCK_50),
		.reset				(~RESET_N)	
);


endmodule